/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controler_Appointement;
import java.awt.Color;
import java.io.File;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import DAO.My_CNX;
import Model.UserList;
import java.sql.Statement;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
/**
 *
 * @author brice
 */
public class Appointement_Medecin extends javax.swing.JFrame {

    /**
     * Creates new form Appointement_Medecin
     */
    private UserList UL;
    private int idp;
    private JComboBox<String> comboBoxL1,comboBoxL2,comboBoxL3,comboBoxL4,comboBoxL5,comboBoxL6;
    private java.sql.Date Lundi= new java.sql.Date(2020-1900,11,15);
    private java.sql.Date Mardi= new java.sql.Date(2020-1900,11,16);
    private java.sql.Date Mercredi= new java.sql.Date(2020-1900,11,17);
    private java.sql.Date Jeudi= new java.sql.Date(2020-1900,11,18);
    private java.sql.Date Vendredi= new java.sql.Date(2020-1900,11,19);
    private java.sql.Date Samedi= new java.sql.Date(2020-1900,11,20);
    public Appointement_Medecin(UserList U,int id) {
        UL=U;
        idp=id;
        comboBoxL1 = new JComboBox<>();
        comboBoxL2 = new JComboBox<>();
        comboBoxL3 = new JComboBox<>();
        comboBoxL4 = new JComboBox<>();
        comboBoxL5 = new JComboBox<>();
        comboBoxL6 = new JComboBox<>();  
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_hind = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jPanel_title = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Search = new javax.swing.JTextField();
        jButton_Search = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel_hind.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_hind.setText(" -");
        jLabel_hind.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_hind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_hindMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_hindMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_hindMouseExited(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_close.setText(" X");
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jPanel_title.setBackground(new java.awt.Color(110, 89, 222));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Search an appointment by Doctor");

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel_hind, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_hind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        jButton5.setBackground(new java.awt.Color(110, 89, 222));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Previous");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Search a Doctor : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_Search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton_Search.setBackground(new java.awt.Color(110, 89, 222));
        jButton_Search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Search.setText("Search");
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null}
            },
            new String [] {
                "", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.setRowHeight(60);
        jScrollPane3.setViewportView(jTable3);

        jButton2.setBackground(new java.awt.Color(110, 89, 222));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Set the appointment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Search)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(403, 403, 403))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jButton5)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String query = "SELECT * FROM appointement WHERE jour = ? AND heureDebut=? AND clinics=?";
        try {
            PreparedStatement st = My_CNX.getConnection().prepareStatement(query);
            if(comboBoxL1.getSelectedIndex()>-1){
                String s=comboBoxL1.getSelectedItem().toString();
                int j=-1;
                for(int i=0;i<UL.getAppList().size();i++){
                    if(UL.getAppList().get(i).toString().equals(s) && UL.getAppList().get(i).getDay().equals(Lundi)){
                        st.setDate(1,UL.getAppList().get(i).getDay());
                        st.setTime(2,UL.getAppList().get(i).getBegin());
                        st.setString(3,UL.getAppList().get(i).getClinic());
                        ResultSet rs= st.executeQuery();
                        if(rs.next())
                        {
                            j=rs.getInt("idAppointement");
                        }
                    }
                }
                Controler_Appointement App= new Controler_Appointement(UL);
                App.takeAppointement(j,idp);
            }
            else if(comboBoxL2.getSelectedIndex()>-1){
                String s=comboBoxL2.getSelectedItem().toString();
                int j=-1;
                for(int i=0;i<UL.getAppList().size();i++){
                    if(UL.getAppList().get(i).toString().equals(s) && UL.getAppList().get(i).getDay().equals(Mardi)){
                        st.setDate(1,UL.getAppList().get(i).getDay());
                        st.setTime(2,UL.getAppList().get(i).getBegin());
                        st.setString(3,UL.getAppList().get(i).getClinic());
                        ResultSet rs= st.executeQuery();
                        if(rs.next())
                        {
                            j=rs.getInt("idAppointement");
                        }
                    }
                }
                Controler_Appointement App= new Controler_Appointement(UL);
                App.takeAppointement(j,idp);
            }
            else if(comboBoxL3.getSelectedIndex()>-1){
                String s=comboBoxL3.getSelectedItem().toString();
                int j=-1;
                for(int i=0;i<UL.getAppList().size();i++){
                    if(UL.getAppList().get(i).toString().equals(s) && UL.getAppList().get(i).getDay().equals(Mercredi)){
                        st.setDate(1,UL.getAppList().get(i).getDay());
                        st.setTime(2,UL.getAppList().get(i).getBegin());
                        st.setString(3,UL.getAppList().get(i).getClinic());
                        ResultSet rs= st.executeQuery();
                        if(rs.next())
                        {
                            j=rs.getInt("idAppointement");
                        }
                    }
                }
                Controler_Appointement App= new Controler_Appointement(UL);
                App.takeAppointement(j,idp);
            }
            else if(comboBoxL4.getSelectedIndex()>-1){
                String s=comboBoxL4.getSelectedItem().toString();
                int j=-1;
                for(int i=0;i<UL.getAppList().size();i++){
                    if(UL.getAppList().get(i).toString().equals(s) && UL.getAppList().get(i).getDay().equals(Jeudi)){
                        st.setDate(1,UL.getAppList().get(i).getDay());
                        st.setTime(2,UL.getAppList().get(i).getBegin());
                        st.setString(3,UL.getAppList().get(i).getClinic());
                        ResultSet rs= st.executeQuery();
                        if(rs.next())
                        {
                            j=rs.getInt("idAppointement");
                        }
                    }
                }
                Controler_Appointement App= new Controler_Appointement(UL);
                App.takeAppointement(j,idp);
            }
            else if(comboBoxL5.getSelectedIndex()>-1){
                String s=comboBoxL5.getSelectedItem().toString();
                int j=-1;
                for(int i=0;i<UL.getAppList().size();i++){
                    if(UL.getAppList().get(i).toString().equals(s) && UL.getAppList().get(i).getDay().equals(Vendredi)){
                        st.setDate(1,UL.getAppList().get(i).getDay());
                        st.setTime(2,UL.getAppList().get(i).getBegin());
                        st.setString(3,UL.getAppList().get(i).getClinic());
                        ResultSet rs= st.executeQuery();
                        if(rs.next())
                        {
                            j=rs.getInt("idAppointement");
                        }
                    }
                }
                Controler_Appointement App= new Controler_Appointement(UL);
                App.takeAppointement(j,idp);
            }
            else if(comboBoxL6.getSelectedIndex()>-1){
                String s=comboBoxL6.getSelectedItem().toString();
                int j=-1;
                for(int i=0;i<UL.getAppList().size();i++){
                    if(UL.getAppList().get(i).toString().equals(s) && UL.getAppList().get(i).getDay().equals(Samedi)){
                        st.setDate(1,UL.getAppList().get(i).getDay());
                        st.setTime(2,UL.getAppList().get(i).getBegin());
                        st.setString(3,UL.getAppList().get(i).getClinic());
                        ResultSet rs= st.executeQuery();
                        if(rs.next())
                        {
                            j=rs.getInt("idAppointement");
                        }
                    }
                }
                Controler_Appointement App= new Controler_Appointement(UL);
                App.takeAppointement(j,idp);
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(Register_form_patient.class.getName()).log(Level.SEVERE, null, ex);
        }
        new Interface_patient(UL, idp).setVisible(true);    // on instancie un objet Form2

        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        // TODO add your handling code here:
        String search;
        search=jTextField_Search.getText();

        String query = "SELECT * FROM medecin WHERE full_name = ?";
        try {
            PreparedStatement st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, search);
            ResultSet rs = st.executeQuery();

            if(rs.next())
            {
                int idM=rs.getInt("idMedecin");
                for(int i=0;i<UL.getAppList().size();i++){
                    if(UL.getAppList().get(i).getDisponible()==1){
                        if(UL.getAppList().get(i).getDay().equals(Lundi) && UL.getAppList().get(i).getIdMed()==idM){
                            comboBoxL1.addItem(UL.getAppList().get(i).toString());
                        }
                        if(UL.getAppList().get(i).getDay().equals(Mardi) && UL.getAppList().get(i).getIdMed()==idM){
                            comboBoxL2.addItem(UL.getAppList().get(i).toString());
                        }
                        if(UL.getAppList().get(i).getDay().equals(Mercredi) && UL.getAppList().get(i).getIdMed()==idM){
                            comboBoxL3.addItem(UL.getAppList().get(i).toString());
                        }
                        if(UL.getAppList().get(i).getDay().equals(Jeudi) && UL.getAppList().get(i).getIdMed()==idM){
                            comboBoxL4.addItem(UL.getAppList().get(i).toString());
                        }
                        if(UL.getAppList().get(i).getDay().equals(Vendredi) && UL.getAppList().get(i).getIdMed()==idM){
                            comboBoxL5.addItem(UL.getAppList().get(i).toString());
                        }
                        if(UL.getAppList().get(i).getDay().equals(Samedi) && UL.getAppList().get(i).getIdMed()==idM){
                            comboBoxL6.addItem(UL.getAppList().get(i).toString());
                        }
                    }
                }

                jTable3.setValueAt(search,0,0);
                jTable3.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(comboBoxL1));
                jTable3.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(comboBoxL2));
                jTable3.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(comboBoxL3));
                jTable3.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(comboBoxL4));
                jTable3.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(comboBoxL5));
                jTable3.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(comboBoxL6));
            }
            else{
                JOptionPane.showMessageDialog(null, "This doctor doesn't exist !");
                new Appointement_Medecin(UL,idp).setVisible(true);
                dispose();
            }

        }
        catch (SQLException ex) {
            Logger.getLogger(Register_form_patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Interface_patient(UL, idp).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered

        // change kes bords en blanc
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_close.setBorder(label_border);
        // Change le trait en blanc
        jLabel_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_hindMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_hindMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_hind.setBorder(label_border);
        jLabel_hind.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_hindMouseExited

    private void jLabel_hindMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_hindMouseEntered

        // change kes bords en blanc
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_hind.setBorder(label_border);
        // Change le trait en blanc
        jLabel_hind.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_hindMouseEntered

    private void jLabel_hindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_hindMouseClicked

    }//GEN-LAST:event_jLabel_hindMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_hind;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField_Search;
    // End of variables declaration//GEN-END:variables
}
